### PR TITLE
TC-R5: Table Abstraction Refactor

### PR DESCRIPTION
**Pull request by NickFrangie**
This is... a bit of a doozy.

All tables now abstract from **TableDisplay**, which acts as a wrapper for configuring **JFXTreeTableView.** Inside each **TableDisplay** class is an embedded **TableDisplayEntry** class, responsible for all the values of a single row of a table.

Even if you don't follow the abstractions and type generic code (my head starts to spin when I think about it too hard), please test it and pay special attention to the implementing classes.

### CODE REVIEW

**Review by mmueting — COMMENTED** [review]
Looked over the all the classes. Looks very impressive. I am not able to run it though. Getting 
Caused by: ERROR X0Y32: Constraint 'FK_REQUESTID' already exists in Schema 'APP'. when I try to run it. Not sure if this is something on my end though.

**Review by MacCode7110 — CHANGES_REQUESTED** [review]
The level of abstraction you implemented makes sense for the complexity of the TreeTableView, the only thing I saw that looked inconsistent was that the LabSystemTableDisplay constructor consumes a LabSystemSR object named medicineDeliverySR. i would make a name change to reflect LabSystemSR, and then this research branch should be all set.

**Comment by NickFrangie** [comment]
> Looked over the all the classes. Looks very impressive. I am not able to run it though. Getting Caused by: ERROR X0Y32: Constraint 'FK_REQUESTID' already exists in Schema 'APP'. when I try to run it. Not sure if this is something on my end though.

make sure to delete DB and re-run whenever you get DB errors

**Review by mmueting — APPROVED** [review]
Looks good

**Pull request merged**
